-- SDK heartbeat, so an empty dashboard stops being unfalsifiable.
--
-- Today a project with no issues renders the same panel whether the app is
-- healthy or the SDK never loaded at all — wrong key, blocked by CORS, module
-- gated off, build shipped without the env var. Every one of those looks
-- exactly like "nothing is broken", and the only way to tell them apart is to
-- deliberately throw an error in production and watch for it.
--
-- These columns are written by POST /sdk/hello, which the SDK calls at most
-- once per browser per day. They record that a real client loaded and
-- identified itself, independently of whether it ever had anything to report.
--
-- Hand-written and additive, following 0000000023-add-repository-to-projects.
-- Deliberately NOT added to 0000000025-create-projects-table.sql: that file is
-- `@generated by buddy migrate:regenerate` and would be overwritten. Do not add
-- an app/Models/*.ts for this either — a new model regenerates every migration
-- from models and deletes the hand-written ones.
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "last_sdk_at" timestamptz;
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "last_sdk_name" varchar(64);
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "last_sdk_version" varchar(32);
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "last_environment" varchar(64);
ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "last_release" varchar(128);
