-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "issues" ALTER COLUMN "title" DROP DEFAULT;
ALTER TABLE "issues" ALTER COLUMN "title" TYPE text USING "title"::text;
ALTER TABLE "issues" ALTER COLUMN "title" SET NOT NULL;
