-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "subscriptions" ALTER COLUMN "type" DROP DEFAULT;
ALTER TABLE "subscriptions" ALTER COLUMN "type" TYPE text USING "type"::text;
ALTER TABLE "subscriptions" ALTER COLUMN "type" SET NOT NULL;
